### ISSUE TITLE
switch the host name, the resources detail area doesn't change.

### ISSUE THREAD

**Issue by jimmy0** [starsliao/Prometheus#44]
![22](https://user-images.githubusercontent.com/4443585/84339200-8324dd80-abd0-11ea-9a09-c54a9b722f2b.png)

the edition is: Node Exporter for Prometheus Dashboard 20200530

**Comment by jimmy0** [comment]
![23](https://user-images.githubusercontent.com/4443585/84355461-3ef80400-abf5-11ea-8f68-6876a44788e9.png)

Resolved.

Should change the row's setting.
change Title from 资源明细表: $show_hostname to 资源明细表: $hostname
Repeat for: hostname

the good show,

**Comment by starsliao** [comment]
> Repeat for

You should use $show_hostname, $show_hostname associated with $node (instance), when you change the instance, $show_hostname will display the correct host name.

Because $hostname has the option of ALL, if you use $hostname, when you change the instance, $hostname cannot display the correct host name.
In addition, there is no need to set Repeat for

**Comment by jimmy0** [comment]
![22](https://user-images.githubusercontent.com/4443585/84756077-ebbaf280-aff4-11ea-9d31-291e120938c2.png)

it shows not good. 

grafana 7.0.3 + prometheus-2.18.1.linux-amd64 + node_exporter-1.0.0.linux-amd64
